language: node_js
node_js:
- '8'
- '10'
os:
- osx
install: 
- npm i
- npm install -g codecov
- npx lerna bootstrap -- --production --no-optional
script: 
# - npx lerna run travis --scope @wxa/core
- npx jest
after_success:
- codecov